### ISSUE TITLE
Use Curve-matcher to compare two trip path

### ISSUE THREAD

**Issue by AsharFatmi** [chanind/curve-matcher#17]
I am trying to compare two different trip path. I have a continuous GPS location from two different trips. and I am trying to compare them to see if they followed the same path. I want to check it non visually this is not on the map. so I used curve-matcher passed all the coordinates in the specified format {x: 24.4197039, y: 54.4416814}. I used shapeSimilarity functionality i got a response 'NaN'.

Code:-
```
const shapeSimilarity = require('curve-matcher');
console.log('done');
let curve1 = [
  {
    "x": 24.4197039,
    "y": 54.4416814
  },
  {
    "x": 24.4197039,
    "y": 54.4416814
  },
  {
    "x": 24.4197039,
    "y": 54.4416814
  },
  {
    "x": 24.4197039,
    "y": 54.4416814
  }
];
let curve2 = [
  {
    "x": 24.4197039,
    "y": 54.4416814
  },
  {
    "x": 24.4197039,
    "y": 54.4416814
  },
  {
    "x": 24.4197039,
    "y": 54.4416814
  },
  {
    "x": 24.4197039,
    "y": 54.4416814
  },
  {
    "x": 24.4197039,
    "y": 54.4416814
  }
];
const similarity = shapeSimilarity.shapeSimilarity(curve1,curve2);
console.log('CONFIDENCE: ',similarity)

```

Console Output:-
```
done

CONFIDENCE:  NaN
```

I reduced the number of points here just for reference. The output is for these points.
But in reality, I will be using around a minimum of 400 points.

Any clue as to why this is happening?

**Comment by chanind** [comment]
This looks like an edge case. I think it's because both curves are just a single point repeated. The library will deduplicate repeated points, so it's like asking how similar 2 curves are that are each just 1 single point. It's sort of a weird calculation to ask how similar 2 points are to each other. In this case, it's the same point, so probably it should have a similarity of 1? But maybe 2 individual points should always return a shape similarity of 1? I mean, they have the same "shape". Or maybe it's best to just throw an error in this case? Probably whatever gets returned when one of the curves is a single point will be nonsensical anyway.

**Comment by AsharFatmi** [comment]
Thank You I fixed this.
